title:              Chan BLOG
email:              wocks3254@gmail.com
description:        
author:             DevJaepaL
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://devjaepal.github.io/"

# Social Profiles
github_username:    DevJaepaL
instagram_username: jaechane

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           6
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
